# Generated by Django 3.2.6 on 2022-03-29 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('name', models.CharField(max_length=1000)),
                ('complaint_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('complaints', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='recharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('completed', 'COMPLETED'), ('pending', 'PENDING')], max_length=1000)),
                ('id_no', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Payment.complaint')),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Payment.complaint')),
            ],
        ),
    ]
